import { StyleSheet } from "react-native";
import { colors } from "../src/colors";
import { fonts } from "../src/fonts";

export const styles = StyleSheet.create({
  button: {
    marginTop: 16,
    alignItems: "center",
    minWidth: 150,
    width: "100%",
    borderRadius: 24,
    backgroundColor: colors.green[400],
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  buttonText: {
    fontFamily: fonts.baiBold,
    fontSize: 14,
    textTransform: "uppercase",
    color: colors.default.bg,
  },
  container: {
    backgroundColor: colors.default.bg,
    flex: 1,
    alignItems: "center",
    justifyContent: "space-evenly",
    paddingVertical: 48,
  },
  titleContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    textAlign: "center",
    fontFamily: fonts.baiBold,
    color: colors.blue[400],
    textTransform: "uppercase",
    fontSize: 20,
  },
  input: {
    backgroundColor: colors.default.bg,
    paddingLeft: 12,
    borderWidth: 1,
    borderColor: colors.green[400],
    height: 40,
    width: "100%",
    minWidth: 165,
    borderRadius: 16,
    fontFamily: fonts.roboto,
  },
  inputContainer: {
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    height: 200,
    paddingHorizontal: 56,
  },
  eventContainer: {
    position: "relative",
    backgroundColor: colors.default.bg,
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 16,
  },
  eventTitle: {
    textAlign: "center",
    fontFamily: fonts.robotoBold,
    color: colors.steel[950],
    fontSize: 30,
  },
  eventDescription: {
    fontFamily: fonts.roboto,
    textAlign: "center",
    color: colors.steel[950],
    fontSize: 48,
  },
  eventTitleContainer: {
    gap: 16,
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 48,
  },
  timerContainer: {
    flex: 1,
    flexDirection: "column",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.default.bg,
    gap: 16,
  },
  eventButton: {
    alignItems: "center",
    width: "45%",
    borderRadius: 24,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  eventButtonContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 24,
    gap: 20,
  },
});
